#! /bin/sh
case "$1" in
  start)
        /home/oficialnosdois/pontos/shs/ajuste-package-json-cme.sh
        ;;
  stop|reload|restart|force-reload|status)
        ;;
  *)
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0